# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


tourneys = ["Battle by the Beach",
"Ara Kumjian Invite",
"Beresford Invite",
"Carlsbad Invite",
"Carter Invite",
"Chester Invite",
"Chowchilla Duals",
"Cossarek Classic",
"Doc Lippman Duals",
"Doc Peterson Invite",
"Dos Palos Invite",
"El Dorado Invite",
"Grizzly Duals",
"Faultine Duals",
"Larry Nelson Classic",
"McNair Invite",
"Newark Rotary Ironman",
"Newbury Park Invite",
"Peninsula Invite",
"Pete Duca Invite",
"Rumble for the Rig",
"Vista Tourney",
"Warrior Invite",
"American Canyon Classic",
"Andrew Pena Invite",
"Bay Area Invite",
"Bear Creek Invite",
"Chukchansi Invite",
"Clovis West Shootout",
"Curt Mettler Invite",
"Eagle Invite",
"Edison Beach Bash",
"Green and Gold",
"Hamada Invite",
"Hawks Nest Invite",
"James Riddle Classic",
"Jesse Cruz Memorial",
"Marauder Invite",
"Nighthawk Duals",
"Northeast Classic",
"Run to Danger",
"Scott Davis Invite",
"Temescal Duals",
"Walsh Ironman",
"Webber Lawson",
"Coyote Classic",
"Al Dingwall",
"Bill Martell Invite",
"California Classic",
"Chris Savedra",
"Colton X-Mas Classic",
"Downey 32-Way",
"Ed Spring Classic",
"El Cajon Invite",
"Folsom Jailbreak Duals",
"Fort Bragg Tourney",
"Healdsburg Duals",
"Las Vegas Holiday Classic",
"Mann Classic",
"Marty Manges Invite",
"Morning Star Invite",
"Napa Valley Classic",
"Rebel Classic",
"Reno TOC",
"West Coast Classic",
"Vista Murrieta Duals",
"Zinkin Classic",
"Brute CA Rumble",
"Deliddo Classic",
"Mike Tamana Invite",
"Lou Bronzan Invite",
"Black Watch",
"Calif. Coast Classic",
"Cerritos TOC",
"No Guts, No Glory",
"Rumble at the Lake",
"Santiago Shark Tank",
"Sierra Nevada Classic",
"The Bash, Don Olson",
"Amaral Memorial",
"Beaumont Tourney",
"Dragon Duals",
"Gordon Hay Invite",
"Oakmont Viking Crusade",
"Pirate Invitational",
"Willemstein Invite",
"Apple Cider Classic",
"ASICS So Cal Challenge",
"Arroyo Classic",
"Bianchini Memorial",
"Bridgetown Throwdown",
"Bulldog Classic",
"Deets Winslow Invite",
"Dennis Jensen Invite",
"Dinuba Invite",
"Doc Buchanan",
"El Camino Invite",
"Holiday Classic",
"Inland Empire TOC",
"Joe Rios Memorial",
"Juan Enriquez Memorial",
"Lancers Invite",
"Mat Classic",
"Nogales SuperChamps",
"Nor Cal Beast",
"NY Revolution",
"Riverside County",
"Sam DeJohn Invite",
"San Ramon Valley Invite",
"SBC Tourney",
"The Dream",
"Anaheim Tourney",
"Armijo Invitational",
"Bert Mar Invite",
"Clayton Valley Invite",
"Five Counties",
"Jim Root Classic",
"Kern County Invite",
"Kroppman Memorial",
"Mark Fuller Invite",
"Redwood Invitational",
"Santa Ynez Tourney",
"Snowden Memorial",
"Sutter Lions Invite",
"Temecula Valley Invite",
"Tim Brown Memorial",
"Troy Invite",
"Westside Classic",
"Centennial Invite",
"CIT",
"Dick Comly",
"Jason White Memorial",
"Kermit Bankson Invite",
"King of the Mat",
"LA Throwdown",
"Laguna Hills Invite",
"Mid Cals",
"Montclair Classic",
"North Coast Classic",
"Raul Huerta Memorial",
"San Clemente Rotary",
"True Wrestler",
"Central Valley Invite",
"Corning Invite",
"Dawn 2 Dusk",
"El Dorado Trojan War",
"Julie Leonard Memorial",
"Lou Encalada Invite",
"Overfelt Classic",
"Pitman Rumble in the Jungle",
"Placer Duals",
"Puma Classic",
"South Bay Invite",
"The Pound"]
