# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


tourneys = ["Battle by the Beach",
"Ara Kumjian Invite",
"Beresford Invite",
"Carlsbad Invite",
"Carter Invite",
"Chester Invite",
"Chowchilla Duals",
"Cossarek Classic",
"Doc Lippman Duals",
"Doc Peterson Invite",
"Dos Palos Invite",
"El Dorado Invite",
"Grizzly Duals",
"Faultine Duals",
"Larry Nelson Classic",
"McNair Invite",
"Newark Rotary Ironman",
"Newbury Park Invite",
"Peninsula Invite",
"Pete Duca Invite",
"Rumble for the Rig",
"Vista Tourney",
"Warrior Invite",
"American Canyon Classic",
"Andrew Pena Invite",
"Bay Area Invite",
"Bear Creek Invite",
"Chukchansi Invite",
"Clovis West Shootout",
"Curt Mettler Invite",
"Eagle Invite",
"Edison Beach Bash",
"Green and Gold",
"Hamada Invite",
"Hawks Nest Invite",
"James Riddle Classic",
"Jesse Cruz Memorial",
"Marauder Invite",
"Nighthawk Duals",
"Northeast Classic",
"Run to Danger",
"Scott Davis Invite",
"Temescal Duals",
"Walsh Ironman",
"Webber Lawson",
"Coyote Classic",
"Al Dingwall",
"Bill Martell Invite",
"California Classic",
"Chris Savedra",
"Colton X-Mas Classic",
"Downey 32-Way",
"Ed Spring Classic",
"El Cajon Invite",
"Folsom Jailbreak Duals",
"Fort Bragg Tourney",
"Healdsburg Duals",
"Las Vegas Holiday Classic",
"Mann Classic",
"Marty Manges Invite",
"Morning Star Invite",
"Napa Valley Classic",
"Rebel Classic",
"Reno TOC",
"West Coast Classic",
"Vista Murrieta Duals",
"Zinkin Classic",
"Brute CA Rumble",
"Deliddo Classic",
"Mike Tamana Invite",
"Lou Bronzan Invite",
"Black Watch",
"Calif. Coast Classic",
"Cerritos TOC",
"No Guts, No Glory",
"Rumble at the Lake",
"Santiago Shark Tank",
"Sierra Nevada Classic",
"The Bash, Don Olson",
"Amaral Memorial",
"Beaumont Tourney",
"Dragon Duals",
"Gordon Hay Invite",
"Oakmont Viking Crusade",
"Pirate Invitational",
"Willemstein Invite",
"Apple Cider Classic",
"ASICS So Cal Challenge",
"Arroyo Classic",
"Bianchini Memorial",
"Bridgetown Throwdown",
"Bulldog Classic",
"Deets Winslow Invite",
"Dennis Jensen Invite",
"Dinuba Invite",
"Doc Buchanan",
"El Camino Invite",
"Holiday Classic",
"Inland Empire TOC",
"Joe Rios Memorial",
"Juan Enriquez Memorial",
"Lancers Invite",
"Mat Classic",
"Nogales SuperChamps",
"Nor Cal Beast",
"NY Revolution",
"Riverside County",
"Sam DeJohn Invite",
"San Ramon Valley Invite",
"SBC Tourney",
"The Dream",
"Anaheim Tourney",
"Armijo Invitational",
"Bert Mar Invite",
"Clayton Valley Invite",
"Five Counties",
"Jim Root Classic",
"Kern County Invite",
"Kroppman Memorial",
"Mark Fuller Invite",
"Redwood Invitational",
"Santa Ynez Tourney",
"Snowden Memorial",
"Sutter Lions Invite",
"Temecula Valley Invite",
"Tim Brown Memorial",
"Troy Invite",
"Westside Classic",
"Centennial Invite",
"CIT",
"Dick Comly",
"Jason White Memorial",
"Kermit Bankson Invite",
"King of the Mat",
"LA Throwdown",
"Laguna Hills Invite",
"Mid Cals",
"Montclair Classic",
"North Coast Classic",
"Raul Huerta Memorial",
"San Clemente Rotary",
"True Wrestler",
"Central Valley Invite",
"Corning Invite",
"Dawn 2 Dusk",
"El Dorado Trojan War",
"Julie Leonard Memorial",
"Lou Encalada Invite",
"Overfelt Classic",
"Pitman Rumble in the Jungle",
"Placer Duals",
"Puma Classic",
"South Bay Invite",
"The Pound"]






"BAC Athenian  Ted Webb  Ted.Webb@athenian.org",
"BAC CSD Michael Sidansky  msidansky@csdf-cde.ca.gov",
"BAC De Anza GorillaMan Arts ucberkeleybears@ymail.com",
"BAC Hercules  Matthew Silva-Thwaites  matthewsilvathwaites@me.com",
"BAC John Swett  A Wilson  awilson@pescm.com",
"BAC Lick Wilmerding Don Rizzi drizzi@lwhs.org",
"BAC Livermore Vly Chtr  Lucas Duckwall  lduckwall@lvcs.org",
"BAC Richmond  Sid Jensen  sid.jensen@asr-group.com",
"BAC St. Pat - St. Vin",

"BVAL  Antioch Brett Mcnamar BrettMcNamar@antioch.k12.ca.us",
"BVAL  Deer Valley Rich Madrigal zeplafied@yahoo.com",
"BVAL  Freedom John Parsons  jparsons@ccwater.com",
"BVAL  Heritage  Mark Barnes mmlbarnes@sbcglobal.net",
"BVAL  Liberty",
"BVAL  Pittsburg Tony Darone tdarone@yahoo.com",

"CMC Clearlake Coach ajpheating@sbcglobal.net",
"CMC Fort Bragg  Coach ryanamundsen72@gmail.com",
"CMC Kelseyville Coach rbrown@pacific.net",
"CMC Lower Lake",
"CMC Middletown  Coach bjh2156@yahoo.com",
"CMC Point Arena Coach patty@mcn.org",
"CMC St Helena Roger Bubel rogerbubel@comcast.net",
"CMC Technology",
"CMC Upper Lake  Coach fernandez0924@sbcglobal.net",
"CMC Willits Coach habitatbuilders707@gmail.com",

"DFAL  Acalanes  Micah Canestaro mcanestaro@gmail.com",
"DFAL  Alhambra  Pep Roa mtzpepper@yahoo.com",
"DFAL  Campolindo  Sam Sotelo  CoachSamSotelo@gmail.com",
"DFAL  Dougherty Valley  Roberto Clemente  rclemente@dvhigh.net",
"DFAL  Dublin  Mike Lemas  coachlemas@gmail.com",
"DFAL  Las Lomas",
"DFAL  Miramonte Jose Herrera  samut50@yahoo.com",

"DVAL  Berean Christian  Darryll Whaley  darryllwhaley@gmail.com",
"DVAL  Clayton Valley  Kyle Behmlander coach@claytonvalleywrestling.com",
"DVAL  College Park  Leroy Rivers  Leroyrivers.b@gmail.com",
"DVAL  Concord Alex Visaya visayaa@mdusd.org",
"DVAL  Mt. Diablo  Shawn Mietz mietz_shawn@hotmail.com",
"DVAL  Northgate",
"DVAL  Ygnacio Valley  Armondo Carrera magazine707@hotmail.com",

"EBAL  Amador  Mark Hamilton mark.hamilton@adp.com",
"EBAL  California  Chris Chamberlain recreationchris@gmail.com",
"EBAL  De La Salle",
"EBAL  Foothill  Dale Hazen  hazendale@gmail.com",
"EBAL  Granada Clark Connover  clarkconover@gmail.com",
"EBAL  Livermore Herby Guidry  caliherb77@yahoo.com",
"EBAL  Monte Vista David Haupt haupt.jd@gmail.com",
"EBAL  San Ramon Valley  Brook Wentner bw77@comcast.net",

"HDNL  Arcata  Coach eric.mikolai@gmail.com",
"HDNL  Del Norte Coach cschaad@co.del-norte.ca.us",
"HDNL  Eureka",
"HDNL  Fortuna Coach steaminhuskies@yahoo.com",
"HDNL  Hoopa Coach  gerbrae@yahoo.com",
"HDNL  McKinleyville Coach vmoorehead@earthlink.net",
"HDNL  South Fork  Coach gratzels@me.com",

"MCAL  Justin Sienna Jason Guiducci  jguiducci@justin-siena.org",
"MCAL  Marin Catholic",
"MCAL  Novato  Garret Heath  faheath@live.com",
"MCAL  Redwood Alan Morris alanjmorris@comcast.net",
"MCAL  San Marin Dan Donaldson snurfer_dan@yahoo.com",
"MCAL  San Rafael  Emmanuel Boyd srhswrestling@gmail.com",
"MCAL  Sir Francis Drake Johann Gerlach  fairmo@gmail.com",
"MCAL  Tamalpais Luke Jones  luke10jones10@gmail.com",
"MCAL  Terra Linda Andre Castvillo andrecast92@gmail.com",

"MVAL  American  Fernando Jose fjose@fremont.k12.ca",
"MVAL  Irvington Michael Damaso  mdamaso@damasoland.com",
"MVAL  JF Kennedy  Robert Nagel  jfkwrestling@yahoo.com",
"MVAL  James Logan",
"MVAL  Mission San Jose  Waylon Miller waylonster@gmail.com",
"MVAL  Newark Memorial Shawn Lambeth Shawn.lambeth@gmail.com",
"MVAL  Washington  Michael Barajas xpalladin@yahoo.com",

"NBL Cardinal Newman Poncho Manriquez  manriquez@cardinalnewman.org",
"NBL Casa Grande Louis Chavez  casagrandewrestling@gmail.com",
"NBL Maria Carrillo",
"NBL Montgomery",
"NBL Rancho Cotate Damien Mason    damien_mason@crpusd.org",
"NBL Santa Rosa  Jay Tiedemann   coachtiedemann@gmail.com",
"NBL Ukiah Thomas Fragoza  tfragoza@uusd.net",
"NBL Windsor Rich Carnation  rich@waterworksindustries.com",

"SCL Analy Ryan Stevens  rstevens.ahs@wscuhsd.k12.ca.us",
"SCL El Molino Blair Moreno  raiderz4bm@gmail.com",
"SCL Elsie Allen Ricardo Alcala  ralcala@srcs.k12.ca.us",
"SCL Healdsburg",
"SCL Petaluma  Paul Schloesser pschloesser@petk12.org",
"SCL Piner Zack Dumas  zdumas@srcs.k12.ca.us",
"SCL Sonoma Valley Tony Albini albini4@sbcglobal.net",

"WACC  Albany",
"WACC  Arroyo  Mike Saenz  msaenz@slzusd.org", 
"WACC  Berkeley  Ben Nathan  gtbenathan@gmail.com",
"WACC  Castro Valley",
"WACC  Hayward Marcel Cheavue  hwdponce1@yahoo.com"
"WACC  Mt Eden Todd Rose toddrose73@yahoo.com",
"WACC  San Leandro David Jagoda  ddjagoda@gmail.com",
"WACC  San Lorenzo",

