class Bout < ActiveRecord::Base
  acts_as_xlsx

  belongs_to :wrestler
  # belongs_to :season_wrestler
  
  validates :weight, presence: true, null: false
  # validates :dual_or_tourney, presence: true, null: false
  
  validates :opponent_name, presence: true, null: false
  validates :win_loss, presence: true, null: false
  # validates :result_type, presence: true, null: false
  validates :score_time, presence: true, null: false
  # validates :opponent_team, presence: true, null: false


  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
     
      puts row
       Bout.create! row.to_hash
      
    end
  end

  def self.download(wrestler)
    CSV.generate do |csv|
      csv << ["wrestler_id", "date", "weight", "dual_or_tourney", "opponent_name", "opponent_team", "result_type", "win_loss", "score_time", "tourney_place", "tourney_name"]
      csv << [ "**  DELETE THESE ROWS BEFORE IMPORTING                            " ]
      csv << [ "**    The following is how each cell should be formatted          " ]
      csv << [ "**     wrestler_id -  autogenerated by this form                  " ]
      csv << [ "**    date - MM/DD/YY format is best                             " ]     
      csv << [ "**     weight -  autogenerated by this form                       " ]
      csv << [ "**     dual_or_tourney -  Enter 'Dual or T'                       " ]
      csv << [ "**     opponent_name -  First and Last                            " ]
      csv << [ "**     opponent_team -  Make sure the school is spelled correctly " ]
      csv << [ "**     result_type -  D, MD, TF, F, FF                            " ]           
      csv << [ "**     win_loss -  W or L                                         " ]
      csv << [ "**     score_time -  ex:  5-1  or  3:27                           " ]
      csv << [ "**     tourney_place -  Only needs to be in there once            " ]      
      csv << [ "**     tourney_name -  be consistent with the spelling            " ] 
      csv << [ "**  DELETE THESE ROWS BEFORE IMPORTING                            " ]     
      csv << [  wrestler.id, "12/16/2017", wrestler.weight, "T", "Steve Johnson", "Arroyo", "MD", "W", "9 -- 1", "1", "Chuck Chansi"]
      csv << [ wrestler.id, "12/16/2017", wrestler.weight, "T", "Bob McPhereson", "Casa Grande", "F", "W", "F 2:38", "", "Chuck Chansi"  ]
      csv << [ wrestler.id, "12/19/2017", wrestler.weight, "DUAL", "Lance Smith", "Gilroy", "D", "L", "2-1" ]
    end
  end

  def self.to_csv(options = {}, example)
    CSV.generate(options) do |csv|
      csv << [ "weight", "last_name", "first_name", "dual_or_tourney", "tourney_name", "tourney_seed", "opponent_team", "opponent_name", "win_loss", "result_type", "score_time", "tourney_place"]

      example.each do |bout|
       csv << [wrestler.weight, wrestler.first_name, wrestler.last_name, wrestler.school.league.name, wrestler.school.name, wrestler.school.abbreviation, wrestler.grade, wrestler.wins, wrestler.losses, wrestler.seed, wrestler.league_place, wrestler.section_place, wrestler.state_place]
      end
    end
  end
end
